[phases.setup]
nixPkgs = ["dotnet-sdk_6"]

[phases.install]
cmds = [
  "dotnet nuget locals all --clear",
  "rm -rf ~/.nuget/packages",
  "dotnet restore HotelApi/HotelApi.csproj --force --verbosity normal"
]

[phases.build]
cmds = ["dotnet publish HotelApi/HotelApi.csproj --no-restore -c Release -o out --verbosity normal"]

[start]
cmd = "./out/HotelApi"
