[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = [
  "dotnet nuget locals all --clear",
  "dotnet restore HotelApi/HotelApi.csproj --force"
]

[phases.build]
cmds = ["dotnet publish HotelApi/HotelApi.csproj --no-restore -c Release -o out"]

[start]
cmd = "./out/HotelApi"
