[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["dotnet restore HotelApi/HotelApi.csproj"]

[phases.build]
cmds = ["dotnet publish HotelApi/HotelApi.csproj --no-restore -c Release -o out"]

[start]
cmd = "./out/HotelApi"
